// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function jsonToinputTut(json) {
  var w0 = json["w10"];
  var w1 = json["w11"];
  if (w0 !== undefined && w1 !== undefined) {
    return /* Some */[/* record */[
              /* w10 */w0,
              /* w11 */w1
            ]];
  } else {
    return /* None */0;
  }
}

function jsonToleaveTut(str) {
  switch (str) {
    case "Run" : 
        return /* Run */0;
    case "Undo" : 
        return /* Undo */2;
    case "Write" : 
        return /* Write */1;
    default:
      throw [
            Caml_builtin_exceptions.match_failure,
            [
              "tutorial.re",
              38,
              3
            ]
          ];
  }
}

var example = /* array */[
  /* array */[
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"Let us start.\n \n          Click the blue stepForward button."
      ],
      /* output : Write */1
    ],
    /* record */[
      /* input : record */[
        /* w10 */"Lemma a(P:Prop):P->P.",
        /* w11 */"Here is your first lemma.\n\n           Note The structure. The general form is: \n \n            Lemma NAME (a:type)...(z:Type): text_of the lemma.\n\n            Note the full stop  at the end. All sentences should end with a fullstop.\n\n           We should now press run. In the tutorial you do not have access to run and undo so press the blue forward button."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"Note that the text has moved up and that you have now a new goal.\n \n          The green statements are the hypotheses and the pink one the conclusion.\n\n          You can click on the hyps and conclusion to get hints.\n \n          Try this for a while to get used with it.\n\n          You can also choose tactics from the menu or type CTRL-Space to autocomplete."
      ],
      /* output : Write */1
    ],
    /* record */[
      /* input : record */[
        /* w10 */"Assume  P then prove  P. ",
        /* w11 */"We now choose the first hint and press run."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"Note the change in the goal. The new conclusion is identical to one of the hypotheses.\n "
      ],
      /* output : Write */1
    ],
    /* record */[
      /* input : record */[
        /* w10 */"This follows from assumptions.",
        /* w11 */"We now finish the proof. "
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"There are no more goals"
      ],
      /* output : Write */1
    ]
  ],
  /* array */[
    /* record */[
      /* input : record */[
        /* w10 */"Lemma a: forall P Q:Prop, P\\/Q->Q\\/P.",
        /* w11 */"This is a lightly more invloved proof and we will see some new tactics.\n Note the structure of the lemma, there are no variables involved, they all appear in the body of the lemma.\n\n          A similar (but shorter) form of the lemma would be:\n Lemma a(P Q:Prop):P\\/Q->Q\\/P.\n You can try it yourself. \n Note also the notation \\/ for OR.\n You could also type \\lor for a better looking OR.\n Press next now."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"Note the formating change in the goals.\n Press the pink button to see what tactics you can choose"
      ],
      /* output : Write */1
    ],
    /* record */[
      /* input : record */[
        /* w10 */"Fix an arbitrary element L.",
        /* w11 */"Indeed, you need to fix a variable in a \"forall\" claim.\n Note that, as usual, the name of the variable you fix is irrelevant so we will call it L instead of P."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"Fix an arbitrary element Q.",
        /* w11 */"Note the substitutions of L for P.\n We use the same tactic for Q as well."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"Assume (L \\/ Q) then prove (Q \\/ L).",
        /* w11 */"Note that your claim is now an implication.\n          As in the first tutorial, we will assume the left hand side of the implication and prove its right hand side."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"Note that the statement (L \\/ Q) became a hypothesis and (Q \\/ L) is the new conclusion. Click on the green button with Hyp: L \\/ Q,  choose the first suggestion and then click next."
      ],
      /* output : Write */1
    ],
    /* record */[
      /* input : record */[
        /* w10 */"Consider cases based on disjunction in hypothesis  Hyp .",
        /* w11 */"This will indeed be a case by case analysis. Click next to see what happens."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"There are now two different goals: The first one has a hypothesis H:P\n the second one  has the hypothesis H:Q.\n Note that at this point you can only attack the first goal so click on the fist tab."
      ],
      /* output : Write */1
    ],
    /* record */[
      /* input : record */[
        /* w10 */"Prove L in the disjunction.",
        /* w11 */"We choose to prove L in the disjunction."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"This follows from assumptions.",
        /* w11 */"This is immediate."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"Prove left hand side.",
        /* w11 */"Note that we are left with the second goal, the case when Q is true.\n We choose a slightly different tactic."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"This follows from assumptions.",
        /* w11 */"Once again we are left with a trivial task.\n Another proof by assumptions finishes the lemma."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"Once again we are done. Pick the tree view from the Actions menu tab to see the proof tree. "
      ],
      /* output : Run */0
    ]
  ],
  /* array */[
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"This is a puzzle due to Lewis Carroll. The story is as follows:\n\n        (a)  All babies are illogical.\n\n(b)  Nobody is despised who can manage a crocodile.\n\n(c)  Illogical persons are dispised.\n\nWe shall deduce that babies cannot manage crocodiles.\n\n        This puzzle will introduce notations and Axioms.\n\n        Click Next"
      ],
      /* output : Write */1
    ],
    /* record */[
      /* input : record */[
        /* w10 */"\nVariable Beings:Set.\nVariables Babies Illogical ManageCroc Despised: Beings->Prop.\n        ",
        /* w11 */"\n        \nFirst  we introduce some variables.\n Note the format:\nVariable NAME:type.\n\nor\nVariables NAME1 NAME2 ... :type.\n\nThe variable Beings is just a \"Set\". That is a special type which, for the moment can be viewed as a set.\n\n The others are \"predicates\" that is function from the Beings to propositions.\n For example \"Illogical x\" would mean that x is illogical.\n\n"
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"\nNotation \"x 'is' 'a' 'Baby' \":=(Babies x) (at level 10).\nNotation \"x 'is' 'illogical' \":=(Illogical x) (at level 10).\nNotation \"x 'is' 'despised' \":=(Despised x) (at level 10).\nNotation \"x 'can' 'manage' 'crocodiles'\":=(ManageCroc x) (at level 10).\n        ",
        /* w11 */"In order to write more naturally sounding statements, we use notations.\n\n        Note the format of notations. It is:\n\n        Notation \" notation\":= FORMULA (at level x).\n\n\n        In the notation, words are separately entered as 'word' and variables are entered as they look. The level part is a bit more complicated. Keep the level at 10 for now.\n"
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"\nAxiom BI: forall x, x is a Baby -> x is illogical.\nAxiom MND : forall x, x can manage crocodiles -> not (x is despised).\nAxiom ID: forall x, x is illogical  -> x is despised.\n        ",
        /* w11 */"(BI)  All babies are illogical.\n\n        (MND)  Nobody is despised who can manage a crocodile.\n\n        (ID)  Illogical persons are despised.\n\n\nNow we introduce the axioms. Note that they look identical with the lemmas but they produce no output. \n"
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"\nLemma LcBabies: forall x,  Babies x-> not (x can manage crocodiles).\n\n        ",
        /* w11 */"Finally here is the lemma we want to prove:\n"
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"\n\n        ",
        /* w11 */"Note that even though we intentionally wrote Babies x in the lemma, the notations we introduced ensure that resulting goal is correctly formated as (x is a Baby).\n"
      ],
      /* output : Write */1
    ],
    /* record */[
      /* input : record */[
        /* w10 */" Fix an arbitrary element B.",
        /* w11 */"We now fix an arbitrary element B and try to prove that is B is a baby then B cannot manage crocodiles."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */" Assume (B is a Baby) then prove (not (B can manage crocodiles)).",
        /* w11 */"As in the previous tutorials, we will assume B is a baby and prove that it cannot manage crocodiles."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */" Rewrite goal using the definition of not.",
        /* w11 */"This is a new tactic, what do you think it menans?"
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"",
        /* w11 */"Note the new goal! The expression  (\xc2\xac P) is a shortcut for P->False."
      ],
      /* output : Write */1
    ],
    /* record */[
      /* input : record */[
        /* w10 */" Assume (B can manage crocodiles) then prove False.",
        /* w11 */"This is again an implication so we use the same tactic."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */" Claim (B is illogical).",
        /* w11 */"This is a forward tactic. We shall first prove the intermediate goals B is illogical. (Hint: Look at the axiom BI)"
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */" \nApply result BI.",
        /* w11 */"As mentioned, the result BI will be used.\n More precisely, due to BI  in order to prove that B is illogical it is enough to prove that B is a baby.\n Click next"
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */" This follows from assumptions.",
        /* w11 */"So we now need to prove that B is a baby. This is one of the assumptions."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */" Obtain (B is despised) applying (ID B) to H.\n    ",
        /* w11 */"This is a shortcut similar with the last two steps.\nWe are executing a forward tactic but we solve the claim directly by applying (ID B) to H.\n Note the two points:\n a) you need to specify (ID B), in the previous tactic B was inffered from the goal \n b) you apply (ID B) to h as if it was a function."
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */" Obtain (not (B is despised)) applying (MND B) to Hyp0.\n    ",
        /* w11 */"This is similar to the above"
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"\n    Apply result H1 .\n    This follows from assumptions.\n    ",
        /* w11 */"Note that we now have both B is despised and not(B is despised). We have two choices. We either directly use tactic \"Apply result (H1 H0).\" or we can do it in three steps as on the left. "
      ],
      /* output : Run */0
    ],
    /* record */[
      /* input : record */[
        /* w10 */"\n    \n    ",
        /* w11 */"We are now done "
      ],
      /* output : Run */0
    ]
  ]
];

exports.jsonToinputTut = jsonToinputTut;
exports.jsonToleaveTut = jsonToleaveTut;
exports.example = example;
/* No side effect */
