// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Js_json = require("bs-platform/lib/js/js_json.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function getText() {
  return (editor2.getValue());
}

function readJson(string) {
  var json = JSON.parse(string);
  var match = Js_json.classify(json);
  if (typeof match === "number") {
    throw [
          Caml_builtin_exceptions.match_failure,
          [
            "utils.re",
            13,
            2
          ]
        ];
  } else {
    switch (match.tag | 0) {
      case 0 : 
          console.log("string" + match[0]);
          return /* () */0;
      case 2 : 
          console.log(Js_primitive.undefined_to_opt(match[0]["input"]));
          return /* () */0;
      case 3 : 
          console.log(match[0]);
          return /* () */0;
      default:
        throw [
              Caml_builtin_exceptions.match_failure,
              [
                "utils.re",
                13,
                2
              ]
            ];
    }
  }
}

exports.getText = getText;
exports.readJson = readJson;
/* No side effect */
