// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./technical/utils.js");
var React = require("react");
var Antd_Icon = require("bs-ant-design/lib/js/src/Antd_Icon.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Antd_IconName = require("bs-ant-design/lib/js/src/Antd_IconName.js");

var loadFile = (function(o)
                {
                    var fr = new FileReader(o);
                    fr.onload = function(e)
                        {
                           editor2.setValue(e.target.result);
                        };
                    fr.readAsText(o.files[0]);
                });

var component = ReasonReact.statelessComponent("ButtonRow");

function handleClick(_, _$1) {
  return /* () */0;
}

function make(forwardTut, occupied, _, onRun, onUndo, _$1, _$2, _$3, _$4) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  key: "box",
                  style: {
                    display: "inline-grid",
                    height: "100%",
                    width: "100%",
                    gridTemplateColumns: "25% 25% 25% 25%"
                  }
                }, React.createElement("button", {
                      key: "run",
                      style: {
                        background: typeof occupied === "number" ? (
                            occupied !== 0 ? "red" : "lightblue"
                          ) : "orange",
                        borderColor: "black",
                        borderStyle: "solid",
                        color: "black",
                        height: "100%",
                        width: "100%"
                      },
                      onClick: typeof occupied === "number" ? (
                          occupied !== 0 ? (function () {
                                return /* () */0;
                              }) : onRun
                        ) : (function () {
                            return /* () */0;
                          })
                    }, "run"), React.createElement("button", {
                      key: "undo",
                      style: {
                        background: typeof occupied === "number" ? (
                            occupied !== 0 ? "red" : "lightblue"
                          ) : "orange",
                        borderColor: "black",
                        borderStyle: "solid",
                        color: "black",
                        height: "100%",
                        width: "100%"
                      },
                      onClick: onUndo
                    }, "undo"), React.createElement("a", {
                      onClick: forwardTut
                    }, ReasonReact.element(/* None */0, /* None */0, Antd_Icon.make(Antd_IconName.stepForward, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[{
                                background: typeof occupied === "number" ? "red" : "lightblue",
                                borderColor: "black",
                                borderStyle: "solid",
                                color: "black",
                                fontSize: "30px",
                                height: "100%",
                                width: "100%"
                              }], /* array */[]))), React.createElement("a", {
                      onClick: (function () {
                          console.log("click");
                          var j = Utils.readJson("{\n      \"input\": {\n        \"w10\": \"string\",\n        \"w11\": \"hhh\"\n      }, \"output\": \"Write\"}\n      ");
                          console.log(j);
                          return /* () */0;
                        })
                    }, ReasonReact.element(/* None */0, /* None */0, Antd_Icon.make(Antd_IconName.stepBackward, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[{
                                background: typeof occupied === "number" ? "red" : "lightblue",
                                borderColor: "black",
                                borderStyle: "solid",
                                color: "black",
                                fontSize: "30px",
                                height: "100%",
                                width: "100%"
                              }], /* array */[]))));
    });
  return newrecord;
}

exports.loadFile = loadFile;
exports.component = component;
exports.handleClick = handleClick;
exports.make = make;
/* loadFile Not a pure module */
