// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var component = ReasonReact.statelessComponent("Lists");

function handleClick(_, _$1) {
  return /* () */0;
}

function make(name, color, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var ss;
      if (name !== "") {
        var butons = $$String.trim(name).split("\n");
        ss = $$Array.mapi((function (s, x) {
                var nr = Js_primitive.null_to_opt(x.match(new RegExp("Lemma"))) !== /* None */0 ? "20px" : "15px";
                var dec = Js_primitive.null_to_opt(x.match(new RegExp("Lemma"))) !== /* None */0 ? "underline" : "none";
                return React.createElement("div", {
                            key: String(s),
                            style: {
                              background: color,
                              fontSize: nr,
                              height: "25px",
                              padding: "0px",
                              textAlign: "left",
                              textDecoration: dec,
                              width: "100%"
                            }
                          }, x);
              }), butons);
      } else {
        ss = /* array */[];
      }
      return React.createElement("div", {
                  style: {
                    background: color,
                    borderStyle: "solid",
                    display: "block",
                    height: "100%",
                    maxHeight: "100%",
                    overflow: "auto",
                    width: "100%"
                  }
                }, ss);
    });
  return newrecord;
}

exports.component = component;
exports.handleClick = handleClick;
exports.make = make;
/* component Not a pure module */
