// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Controller = require("./Controller.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var main = ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Controller.make(/* array */[React.createElement("textarea", {
                    key: "0",
                    style: {
                      backgroundColor: "white",
                      fontSize: "16px",
                      maxHeight: "100%",
                      minHeight: "100%",
                      alignSelf: "left"
                    }
                  })])), "root");

exports.main = main;
/* main Not a pure module */
