// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var HypLists = require("./HypLists.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Col$BsReactstrap = require("bs-reactstrap/lib/js/src/Col.bs.js");
var Nav$BsReactstrap = require("bs-reactstrap/lib/js/src/Nav.bs.js");
var Row$BsReactstrap = require("bs-reactstrap/lib/js/src/Row.bs.js");
var NavItem$BsReactstrap = require("bs-reactstrap/lib/js/src/NavItem.bs.js");
var NavLink$BsReactstrap = require("bs-reactstrap/lib/js/src/NavLink.bs.js");
var TabPane$BsReactstrap = require("bs-reactstrap/lib/js/src/TabPane.bs.js");
var TabContent$BsReactstrap = require("bs-reactstrap/lib/js/src/TabContent.bs.js");

var component = ReasonReact.reducerComponent("MyNTabs");

function make(text, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var butons = text.split("\n\n");
      ReasonReact.element(/* Some */["Aaa"], /* None */0, Nav$BsReactstrap.make(/* Some */[(true)], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[$$Array.mapi((function (s, _) {
                        var ss = String(s + 1 | 0);
                        return ReasonReact.element(/* Some */[String(s + 1 | 0)], /* None */0, NavItem$BsReactstrap.make(/* None */0, /* None */0, /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, NavLink$BsReactstrap.make(/* None */0, /* Some */["#" + (String(ss) + "")], /* None */0, /* None */0, /* Some */[s === 0 ? "active" : ""], /* None */0, /* Some */[(function () {
                                                      var tab = String(s);
                                                      if (self[/* state */2][/* activeTab */0] !== tab) {
                                                        return Curry._1(self[/* send */4], /* Toggle */[tab]);
                                                      } else {
                                                        return 0;
                                                      }
                                                    })], /* None */0, /* array */["  Goal  " + (String(s + 1 | 0) + "   ")]))]));
                      }), butons)]));
      return ReasonReact.element(/* None */0, /* None */0, TabContent$BsReactstrap.make(/* None */0, /* Some */[self[/* state */2][/* activeTab */0]], /* None */0, /* None */0, /* array */[$$Array.mapi((function (s, x) {
                              return ReasonReact.element(/* Some */[x], /* None */0, TabPane$BsReactstrap.make(/* None */0, /* None */0, /* None */0, /* Some */[String(s + 1 | 0)], /* array */[ReasonReact.element(/* None */0, /* None */0, Row$BsReactstrap.make(/* None */0, /* None */0, /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Col$BsReactstrap.make(/* None */0, /* None */0, /* Some */["12"], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, HypLists.make(x, /* array */[]))]))]))]));
                            }), butons)]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* activeTab */"1"];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* activeTab */action[0]]]);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
