// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Tab = require("/Users/Hoff/Documents/reactut/a-reason-react-tutorial/node_modules/react-bootstrap/lib/Tab");

function make(title, children) {
  return ReasonReact.wrapJsForReason(Tab.default, {
              title: title
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
