// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Modal$BsReactstrap = require("bs-reactstrap/lib/js/src/Modal.bs.js");
var Button$BsReactstrap = require("bs-reactstrap/lib/js/src/Button.bs.js");
var ModalBody$BsReactstrap = require("bs-reactstrap/lib/js/src/ModalBody.bs.js");
var ModalFooter$BsReactstrap = require("bs-reactstrap/lib/js/src/ModalFooter.bs.js");
var ModalHeader$BsReactstrap = require("bs-reactstrap/lib/js/src/ModalHeader.bs.js");

var component = ReasonReact.statelessComponent("Save");

function make(content, see, toggle, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var ssave = (
        function (text, file)
        {let blob= new Blob([text], {type: "text/plain;charset=utf-8"});
        saveAs(blob, file)});
      return ReasonReact.element(/* None */0, /* None */0, Modal$BsReactstrap.make(/* Some */[see], /* None */0, /* None */0, /* None */0, /* Some */[toggle], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                      ReasonReact.element(/* None */0, /* None */0, ModalHeader$BsReactstrap.make(/* None */0, /* None */0, /* Some */[toggle], /* None */0, /* None */0, /* None */0, /* array */["Save file:"])),
                      ReasonReact.element(/* None */0, /* None */0, ModalBody$BsReactstrap.make(/* None */0, /* None */0, /* None */0, /* array */[React.createElement("div", undefined, "File Name:", React.createElement("input", {
                                          className: "saveText"
                                        }))])),
                      ReasonReact.element(/* None */0, /* None */0, ModalFooter$BsReactstrap.make(/* None */0, /* None */0, /* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Button$BsReactstrap.make(/* None */0, /* None */0, /* Some */["primary"], /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                              var aa = Caml_array.caml_array_get(document.getElementsByClassName("saveText"), 0);
                                              var fileName = aa.value;
                                              return Curry._2(ssave, content, fileName);
                                            })], /* None */0, /* None */0, /* None */0, /* array */["Save"]))]))
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
