// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var MyTab = require("./myTab.js");
var MyTabs = require("./myTabs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function str() {
  return (function (prim) {
      return prim;
    });
}

var component = ReasonReact.statelessComponent("Tabbed");

function handleClick(_, _$1) {
  return /* () */0;
}

function handleSelect(key) {
  console.log(key);
  return /* () */0;
}

function make(name, _, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      name.split("\n\n");
      return ReasonReact.element(/* None */0, /* None */0, MyTabs.make("self.handle(handleClick)", /* array */[
                      ReasonReact.element(/* None */0, /* None */0, MyTab.make("Tab 1", /* array */["  aaa"])),
                      ReasonReact.element(/* None */0, /* None */0, MyTab.make("Tab 2", /* array */["  bbb"])),
                      ReasonReact.element(/* None */0, /* None */0, MyTab.make("Tab 3", /* array */["   ccc  "]))
                    ]));
    });
  return newrecord;
}

exports.str = str;
exports.component = component;
exports.handleClick = handleClick;
exports.handleSelect = handleSelect;
exports.make = make;
/* component Not a pure module */
