// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("TodoApp");

function handleClick(_, _$1) {
  return /* () */0;
}

function make(children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: {
                    background: "green",
                    display: "inline-grid",
                    fontSize: "68px",
                    height: "100%",
                    width: "100%",
                    alignSelf: "left",
                    gridTemplateColumns: "auto auto",
                    gridTemplateRows: "45% 45% 10%"
                  }
                }, (console.log(Caml_array.caml_array_get(children, 0)), children));
    });
  return newrecord;
}

exports.component = component;
exports.handleClick = handleClick;
exports.make = make;
/* component Not a pure module */
